### ISSUE TITLE
Python script shebangs should use `/usr/bin/env python`

### ISSUE THREAD

**Issue by BBaoVanC** [kendallgoto/ilo4_unlock#18]
Currently all the python files have a `#!/usr/bin/python` shebang, which forces the Python version installed system wide to be used. This doesn't sound intentional as the README says to create a virtualenv to install requirements in. Using a shebang of `#!/usr/bin/env python` would allow using the actual Python version inside the virtualenv and ensure that everything happens inside.

**Comment by kendallgoto** [comment]
as far as i can tell, all of this repo's python scripts properly use /usr/bin/env. however, the dependent scripts from airbus likely do not. I can't really do anything about that, aside from fixing them if/when I rewrite their scripts and remove the dependency
