### ISSUE TITLE
Not seeing output from any command

### ISSUE THREAD

**Issue by Crylia** [kendallgoto/ilo4_unlock#22]
It seems like the commands are working, but I don't get any output like `fan info`.

I'm on a ml350 gen9 with the patched ilo4 2.77

**Comment by Crylia** [comment]
Never mind, I had to reset the ilo (that was probably meant with power off, not just shut down)

**Comment by brettinternet** [comment]
@kendallgoto I ran into this and had to reset the iLO. After rebooting I'm not seeing any output again. Do I have to reset the iLO each time I want to configure a fan?

```
</>hpiLO-> fan info



</>hpiLO->
```

**Comment by kendallgoto** [comment]
you have to reset iLO every time you want to see the output of the command, not every time you want to configure the fan itself. the commands still work even if the output isn't shown, it just isn't helpful for commands that only show information (like fan info). 

also, on a single SSH session, the output will continue to work. it'll just stop working if you create a new ssh session.

**Comment by brettinternet** [comment]
I see, thank you for the help!

**Comment by kendallgoto** [comment]
> Can you reset to default settings if you messed up? Does reset iLO from health page reset the fan to factory? Or Reboot? 

iLO reset from the webpage will reset it. nothing is persistent
