### ISSUE TITLE
Successful flash on ML110 Gen9

### ISSUE THREAD

**Issue by TizzAmmazz** [kendallgoto/ilo4_unlock#23]
I just wanted to report that I successfully flashed the modded firmware on my Proliant ML110 Gen9 without any deviation from the provided guide.

I used a fresh install of Ubuntu 20.04 LTS to build the firmware and a Ventoy USB liveCD Ubuntu 20.04 LTS to flash it.

DIP switch on motherboard is number 1 as per official docs.

**Comment by kendallgoto** [comment]
thanks for sharing!
