### ISSUE TITLE
fan command not working after power off

### ISSUE THREAD

**Issue by pfandl** [kendallgoto/ilo4_unlock#25]
Hello, first thanks for this stuff! I could get it flashed correctly, its just that after i power off (reset is fine iirc) the machine, the fan command stops working, it just gives me couple of empty lines back. Does somebody know what is wrong here?

**Comment by jerryfudd** [comment]
any settings you make don't hold past a reset so I've added a command in the start up to passwordless ssh to re-apply on every reboot.

I've also had the issue where trying to get output produces no response on some Terminal apps, but as sending the commands to turn the fans down works for now I've not looked into it any further.

I make sure the private key for the machine is set for the user in the iLO webpage and then send the following command for each fan to set it to 25% on reboot

ssh <ilo user>@<ilo ip> -o PubKeyAcceptedKeyTypes=+ssh-rsa -o HostKeyAlgorithms=+ssh-dss -o KexAlgorithms=+diffie-hellman-group14-sha1 "fan p 0 max 64"

0 is the fan # 
64 is the value for 25%

**Comment by pfandl** [comment]
@jerryfudd Thank you very much, you are right! There is not output but it will still set the values. Also thanks for `-o PubKeyAcceptedKeyTypes=+ssh-rsa` now i can login without password, awesome!
