### ISSUE TITLE
ImportError: No module named keystone

### ISSUE THREAD

**Issue by bladedevoff** [kendallgoto/ilo4_unlock#27]
Hi, guys! I'm just trying to make my DL380P quiet. I'm running on Ubuntu Livecd with script in releases and toggled off ILO Security. But when script is flashing - ImportError module keystone. I tried to install keystone manually, but it's not installing. 
![17228422478562303045696892725996](https://github.com/user-attachments/assets/9e3749ad-f138-4aaa-9f1a-461a5dfbdc98)

**Comment by kendallgoto** [comment]
can you install the requirements.txt
eg pip install -r requirements.txt

i believe keystone is called keystone-engine in pypi
