### ISSUE TITLE
DL20 Gen9 - Proxmox/debian

### ISSUE THREAD

**Issue by Logikoz** [kendallgoto/ilo4_unlock#28]
i have successfully install on ubuntu server 22 in same machine.

but, after change OS for proxmox/debian, scripts dont works...

this is my changes to "works".

```
apt install git
apt install python3
apt install python3.11-venv
git clone --recurse-submodules https://github.com/kendallgoto/ilo4_unlock.git
cd ilo4_unlock

python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt

./build.sh init
./build.sh 277  # ERROR HERE
```
on run "./build.sh 277", output is:
```
(venv) root@lks001:~/ilo4_unlock# ./build.sh 277
Hash validated for binaries/ilo4_277.bin
Extracting with iLO4 Toolbox ...
```

but dont generated any file...

**anyware sugestion?**

**Comment by Risusama** [comment]
The scripts don't work with Python3. Use Python2.

**Comment by Logikoz** [comment]
Do you have plans to upgrade to Python3?

**Comment by kendallgoto** [comment]
it's tracked in #16. generally i'm looking to just remove our externally dependencies entirely but i haven't had time to look at it. All of this repo is python3 compatible, there's an upstream dependency that's only on python2 that I don't control

**Comment by Logikoz** [comment]
i have more one problem:

root@lks001:~/flash# ./flash_ilo4 --direct
-bash: ./flash_ilo4: Permission denied


any suggestion?

**Comment by kendallgoto** [comment]
probably
`chmod +x ./flash_ilo4`?

**Comment by Logikoz** [comment]
Aaaaaaaaaaaaaaaaaa I managed to solve it!

here my solution for all the problem:

Create a Virtual Machine with ubuntu server 22 image in the same machine dl20 g9 proxmox/debian, and execute all commands from docs on this repo.

stop commands on tihs line:
![image](https://github.com/user-attachments/assets/78a04d8e-51a3-4dfa-99c9-f54a5ec82635)

after, connect in your VM using FTP, and copy /flash folder to your personal machine.

now, connect into proxmox machine (dl20 g9) using ftp, and paste the same folder /flash.

after, using ssh, access your proxmox machine and execute this commands:

```
//enter in your machine folder where you paste /flash folder using ftp
cd flash 

//run the command
./flash_ilo4 --direct

//if show permission error, run this command
chmod +x flash_ilo4

//and run again
./flash_ilo4 --direct

```
